import { Candle, CategoryMeta } from './types';

export const CATEGORY_META: CategoryMeta[] = [
  { name: 'Fresh',  subtitle: 'Bright, airy, and sun-drenched — for every kind of good day.' },
  { name: 'Warm',   subtitle: 'Cozy, indulgent, and deeply comforting — like a hug in a jar.' },
  { name: 'Floral', subtitle: 'Soft petals and romantic notes — beautifully timeless.' },
  { name: 'Earthy', subtitle: 'Grounded, smoky, and mysterious — nature distilled.' },
];

export const CANDLES: Candle[] = [
  {
    id: 'c1',
    name: 'Golden Hour',
    artist: 'JVKE',
    scent: 'Sunset Sorbet',
    description: 'Sweet citrus meets ripe peach in this golden, sun-kissed blend that captures the last light of day.',
    image: 'https://picsum.photos/id/1060/800/800',
    spotifyTrackId: '4yNk9iz9WVJikRFle3XEvn',
    price: 32,
    stock: 1,
    scentProfile: ['Citrus', 'Peach', 'Mango'],
    category: 'Fresh',
  },
  {
    id: 'c2',
    name: 'Eternal Sunshine',
    artist: 'Lou Val',
    scent: 'Ocean Mist',
    description: 'A breath of fresh ocean air and sun-warmed coconut, lifting your spirits like a perfect summer morning.',
    image: 'https://picsum.photos/id/1050/800/800',
    spotifyTrackId: '5FChOu6NfR5w7YLgDmXXnC',
    price: 30,
    stock: 1,
    scentProfile: ['Sea Salt', 'Fresh Air', 'Coconut'],
    category: 'Fresh',
  },
  {
    id: 'c3',
    name: 'Lake Missoula',
    artist: 'Richy Mitch & The Coal Miners',
    scent: 'Vanilla Pumpkin Marshmallow',
    description: 'Rich vanilla and spiced pumpkin wrapped in soft marshmallow — the coziest candle for cool evenings.',
    image: 'https://picsum.photos/id/292/800/800',
    spotifyTrackId: '4x1dWc1GgAfC04GcTlllax',
    price: 34,
    stock: 1,
    scentProfile: ['Vanilla', 'Pumpkin', 'Marshmallow'],
    category: 'Warm',
  },
  {
    id: 'c4',
    name: 'Weekend Friend',
    artist: 'Goth Babe',
    scent: 'Coconut Mango',
    description: 'Tropical coconut and juicy mango transport you straight to a carefree weekend getaway.',
    image: 'https://picsum.photos/id/429/800/800',
    spotifyTrackId: '2d3QlXE6FXFDeodiS66yjM',
    price: 32,
    stock: 1,
    scentProfile: ['Coconut', 'Mango', 'Tropical'],
    category: 'Fresh',
  },
  {
    id: 'c5',
    name: 'Coast',
    artist: 'Hailee Steinfeld',
    scent: 'Ocean Mist',
    description: 'Salty sea breeze and fresh coastal air bottled into a crisp, clean burn that clears the mind.',
    image: 'https://picsum.photos/id/1015/800/800',
    spotifyTrackId: '1l4iQsOZ5sOXZPMQLvouaB',
    price: 30,
    stock: 1,
    scentProfile: ['Sea Salt', 'Fresh Air', 'Driftwood'],
    category: 'Fresh',
  },
  {
    id: 'c6',
    name: 'Sunshine, Lollipops and Rainbows',
    artist: 'Lesley Gore',
    scent: 'Fruit Rings',
    description: 'Playful and sweet — a cheerful blend of mixed berries and citrus zest, pure uncomplicated joy.',
    image: 'https://picsum.photos/id/139/800/800',
    spotifyTrackId: '3bpxXrU2ZtpmN1tyVmaO6S',
    price: 28,
    stock: 1,
    scentProfile: ['Citrus', 'Berry', 'Sweet'],
    category: 'Fresh',
  },
  {
    id: 'c7',
    name: 'Tomorrow',
    artist: 'Shakey Graves',
    scent: 'Apple Cider Donut',
    description: 'Warm apple cider and fresh-baked donut spices — the hopeful scent of autumn mornings and new beginnings.',
    image: 'https://picsum.photos/id/312/800/800',
    spotifyTrackId: '7xrgjsuZwFtv25ELEMKkpl',
    price: 32,
    stock: 1,
    scentProfile: ['Apple', 'Cinnamon', 'Brown Sugar'],
    category: 'Warm',
  },
  {
    id: 'c8',
    name: 'A Sunday Kind of Love',
    artist: 'Etta James',
    scent: 'Rose',
    description: 'A timeless rose with a soft musk heart — romantic, unhurried, and deeply comforting.',
    image: 'https://picsum.photos/id/152/800/800',
    spotifyTrackId: '0zGLlXbHlrAyBN1x6sY0rb',
    price: 34,
    stock: 1,
    scentProfile: ['Rose', 'Floral', 'Musk'],
    category: 'Floral',
  },
  {
    id: 'c9',
    name: 'Espresso',
    artist: 'Sabrina Carpenter',
    scent: 'Coffee',
    description: 'Bold espresso meets warm vanilla in a rich, energizing blend for slow mornings and late nights.',
    image: 'https://picsum.photos/id/425/800/800',
    spotifyTrackId: '2qSkIjg1o9h3YT9RAgYN75',
    price: 30,
    stock: 1,
    scentProfile: ['Coffee', 'Espresso', 'Vanilla'],
    category: 'Warm',
  },
  {
    id: 'c10',
    name: 'Lavender Haze',
    artist: 'Taylor Swift',
    scent: 'Lavender',
    description: 'Dreamy lavender in a soft herbal haze — the scent of calm, quiet, and drifting into sleep.',
    image: 'https://picsum.photos/id/164/800/800',
    spotifyTrackId: '5jQI2r1RdgtuT8S3iG8zFC',
    price: 32,
    stock: 1,
    scentProfile: ['Lavender', 'Herbal', 'Floral'],
    category: 'Floral',
  },
  {
    id: 'c11',
    name: 'Congratulations',
    artist: 'Mac Miller',
    scent: 'Love Spell',
    description: 'A playful mix of peach blossom and cherry with a warm musk base — celebratory and irresistibly warm.',
    image: 'https://picsum.photos/id/1080/800/800',
    spotifyTrackId: '1OubIZ0ARYCUq5kceYUQiO',
    price: 34,
    stock: 1,
    scentProfile: ['Peach', 'Cherry Blossom', 'Musk'],
    category: 'Floral',
  },
  {
    id: 'c12',
    name: 'Feels Like Summer',
    artist: 'Childish Gambino',
    scent: 'Mango Coconut',
    description: 'Sun-drenched mango and creamy coconut that make every room feel like a golden summer afternoon.',
    image: 'https://picsum.photos/id/28/800/800',
    spotifyTrackId: '1FDYlHFZpKDOBjp2TaKfP6',
    price: 32,
    stock: 1,
    scentProfile: ['Mango', 'Coconut', 'Tropical'],
    category: 'Fresh',
  },
  {
    id: 'c13',
    name: 'Wildfire',
    artist: 'Cautious Clay',
    scent: 'Fallen Leaves',
    description: 'Smoky cedarwood and autumn leaves with an ember heart — wild, warm, and beautifully free.',
    image: 'https://picsum.photos/id/1043/800/800',
    spotifyTrackId: '69xOrL71OeGz5fqXFTnJ5L',
    price: 34,
    stock: 1,
    scentProfile: ['Cedarwood', 'Autumn Leaves', 'Smoke'],
    category: 'Earthy',
  },
  {
    id: 'c14',
    name: 'I Love You So',
    artist: 'The Walters',
    scent: 'Cinnamon Buns',
    description: 'Freshly baked cinnamon buns with a sweet vanilla glaze — the most comforting scent in the world.',
    image: 'https://picsum.photos/id/431/800/800',
    spotifyTrackId: '4SqWKzw0CbA05TGszDgMlc',
    price: 32,
    stock: 1,
    scentProfile: ['Cinnamon', 'Vanilla', 'Brown Sugar'],
    category: 'Warm',
  },
  {
    id: 'c15',
    name: 'Champagne Supernova',
    artist: 'Oasis',
    scent: 'Champagne Toast',
    description: 'Bright champagne bubbles and sparkling citrus zest — effervescent, celebratory, and impossibly light.',
    image: 'https://picsum.photos/id/667/800/800',
    spotifyTrackId: '6EMynpZ10GVcwVqiLZj6Ye',
    price: 36,
    stock: 1,
    scentProfile: ['Champagne', 'Citrus', 'White Flowers'],
    category: 'Fresh',
  },
  {
    id: 'c16',
    name: 'Angel',
    artist: 'Massive Attack',
    scent: 'Black Ice',
    description: 'Cool bergamot and smoky cedar wrapped in a deep, mysterious musk. Dark, beautiful, otherworldly.',
    image: 'https://picsum.photos/id/101/800/800',
    spotifyTrackId: '5ZCc9E9FsPlxFsLDVcgLsK',
    price: 34,
    stock: 1,
    scentProfile: ['Musk', 'Bergamot', 'Cedar'],
    category: 'Earthy',
  },
  {
    id: 'c17',
    name: 'Better Together',
    artist: 'Jack Johnson',
    scent: 'Blueberry Cobbler',
    description: 'Sweet blueberries and golden pastry crust with warm spice — the smell of togetherness.',
    image: 'https://picsum.photos/id/102/800/800',
    spotifyTrackId: '4VywXu6umkIQ2OS0m1I79y',
    price: 30,
    stock: 1,
    scentProfile: ['Blueberry', 'Vanilla', 'Warm Spice'],
    category: 'Warm',
  },
  {
    id: 'c18',
    name: 'Sweater Weather',
    artist: 'The Neighbourhood',
    scent: 'Sweater Weather',
    description: 'Soft cashmere and warm sandalwood with cozy spice notes — made for curling up indoors.',
    image: 'https://picsum.photos/id/116/800/800',
    spotifyTrackId: '2QjOHCTQ1Jl3zawyYOpxh6',
    price: 32,
    stock: 1,
    scentProfile: ['Cashmere', 'Sandalwood', 'Warm Spice'],
    category: 'Warm',
  },
  {
    id: 'c19',
    name: 'Slow Dancing in a Burning Room',
    artist: 'John Mayer',
    scent: 'Cedar Musk and Lavender',
    description: 'Cedarwood, soft lavender, and a warm musk that feels like slow dancing at the end of a long night.',
    image: 'https://picsum.photos/id/130/800/800',
    spotifyTrackId: '2jdAk8ATWIL3dwT47XpRfu',
    price: 36,
    stock: 1,
    scentProfile: ['Cedarwood', 'Lavender', 'Musk'],
    category: 'Earthy',
  },
  {
    id: 'c20',
    name: 'Purple Roses',
    artist: 'Slow Funeral',
    scent: 'Wildberry Tulip',
    description: 'Wild berries and fresh tulip petals in a delicate floral blend — bittersweet and unforgettable.',
    image: 'https://picsum.photos/id/1084/800/800',
    spotifyTrackId: '6wfl32rXBpn5MC3ZzZKafM',
    price: 32,
    stock: 1,
    scentProfile: ['Berry', 'Tulip', 'Fresh Floral'],
    category: 'Floral',
  },
];
